"""
module2_shuttle_detection.py
════════════════════════════
Shuttlecock 2-D pixel extraction  →  (u, v) per frame

This module is written against the ACTUAL TrackNetV3 predict.py interface
(qaz812345/TrackNetV3).  Every argument name, file name, and CSV column
matches the real script exactly — verified from predict.py source.

TrackNetV3 predict.py argument mapping
───────────────────────────────────────
  --video_file        path to the video
  --tracknet_file     path to TrackNet_best.pt
  --inpaintnet_file   path to InpaintNet_best.pt   (optional)
  --save_dir          directory for outputs  (NOT --output_csv)
  --eval_mode         nonoverlap | average | weight  (default: weight)
  --batch_size        (default: 16)
  --large_video       flag for large videos
  --output_video      flag to also write annotated mp4

Output CSV name (auto-generated by TrackNetV3):
  {save_dir}/{video_stem}_ball.csv

CSV columns (TrackNetV3 format):
  Frame, Visibility, X, Y
  Visibility: 1 = detected, 0 = not detected

Pipeline
────────
  1. Validates weights folder and both .pt files exist.
  2. Runs predict.py as a subprocess with correct argument names.
  3. Locates the auto-named CSV ({video_stem}_ball.csv) in save_dir.
  4. Parses CSV → (N_frames, 2) float64; NaN where Visibility == 0.
  5. Aligns array length to actual video frame count (handles edge cases).
  6. Gaussian smoothing on detected positions only.
  7. Linear interpolation over short gaps (≤ GAP_FILL_FRAMES).
  8. Saves shuttle_2d.npy + debug video.

Usage
─────
  python module2_shuttle_detection.py
  python module2_shuttle_detection.py \\
      --video    clip.mp4 \\
      --tracknet ./tracknet_weights \\
      --out_dir  shuttle_out

  # Pass extra TrackNetV3 flags through --tn_args:
  python module2_shuttle_detection.py \\
      --video  clip.mp4 \\
      --tracknet ./tracknet_weights \\
      --tn_eval_mode nonoverlap \\
      --tn_batch_size 8 \\
      --tn_large_video

Outputs
───────
  shuttle_out/shuttle_2d.npy          (N_frames, 2) float64; NaN = undetected
  shuttle_out/shuttle_detection.mp4   debug video: green dot + amber trail
  shuttle_out/detection_stats.txt     detection rate + quality grade
  shuttle_out/tracknet_raw/           raw TrackNetV3 outputs (CSV + optional mp4)
"""

import argparse
import csv
import subprocess
import sys
from pathlib import Path

import cv2
import numpy as np
from scipy.ndimage import gaussian_filter1d

sys.path.insert(0, str(Path(__file__).parent))
from config import VIDEO_PATH, TRACKNET_DIR, SHUTTLE_OUT

# ── Tuning knobs ──────────────────────────────────────────────────────────────
SMOOTH_SIGMA    = 1.2   # Gaussian σ on detected-frame positions
GAP_FILL_FRAMES = 5     # interpolate NaN gaps ≤ this many frames
TRAIL_LEN       = 20    # frames of amber trail drawn in debug video

# ── TrackNetV3 exact weight filenames (from the official repo) ────────────────
TRACKNET_PT   = "TrackNet_best.pt"     # capital T, capital N
INPAINTNET_PT = "InpaintNet_best.pt"   # capital I, capital N


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 1 — VALIDATE WEIGHTS FOLDER
# ─────────────────────────────────────────────────────────────────────────────
def _validate_weights(weights_dir: Path):
    """
    Confirm predict.py and both .pt files are present.
    Raises FileNotFoundError with a helpful message if anything is missing.
    """
    missing = []
    for fname in ["predict.py", TRACKNET_PT, INPAINTNET_PT]:
        if not (weights_dir / fname).exists():
            missing.append(fname)

    if missing:
        raise FileNotFoundError(
            f"Missing files in {weights_dir}:\n"
            + "".join(f"  ✗  {m}\n" for m in missing)
            + "\nExpected layout:\n"
            "  tracknet_weights/\n"
            "    ├── predict.py\n"
            f"    ├── {TRACKNET_PT}\n"
            f"    └── {INPAINTNET_PT}\n"
            "\nDownload checkpoints from the TrackNetV3 Google Drive link\n"
            "in the README and unzip into your weights folder."
        )


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 2 — RUN TRACKNETV3 predict.py
# ─────────────────────────────────────────────────────────────────────────────
def run_tracknet(
    video_path: str,
    weights_dir: str,
    raw_out_dir: str,
    eval_mode: str  = "weight",
    batch_size: int = 4,
    large_video: bool = False,
) -> Path:
    """
    Call TrackNetV3 predict.py with the CORRECT argument names and return
    the path to the auto-generated CSV file.

    TrackNetV3 argument names (verified from predict.py source)
    ────────────────────────────────────────────────────────────
      --video_file          ← NOT --video
      --tracknet_file       ← NOT --tracknet
      --inpaintnet_file     ← NOT --inpaintnet
      --save_dir            ← output folder; CSV auto-named {stem}_ball.csv
      --eval_mode           nonoverlap | average | weight
      --batch_size
      --large_video         store_true flag

    Returns
    ───────
    Path to the CSV file:  {raw_out_dir}/{video_stem}_ball.csv
    """
    wd  = Path(weights_dir).resolve()
    _validate_weights(wd)

    raw_dir = Path(raw_out_dir).resolve()   # MUST be absolute — TrackNet joins
    raw_dir.mkdir(parents=True, exist_ok=True)  # save_dir + video_stem on Windows

    # Use only the filename stem (no directory component) as the video identifier.
    # On Windows, video_path.split('/')[-1] returns the whole relative path if
    # the path uses backslashes — Path().stem handles both separators correctly.
    video_stem   = Path(video_path).stem
    expected_csv = raw_dir / f"{video_stem}_ball.csv"

    cmd = [
        sys.executable, str(wd / "predict.py"),
        "--video_file",     str(Path(video_path).resolve()),  # absolute
        "--tracknet_file",  str(wd / TRACKNET_PT),
        "--inpaintnet_file",str(wd / INPAINTNET_PT),
        "--save_dir",       str(raw_dir),   # absolute — no path doubling
        "--eval_mode",      eval_mode,
        "--batch_size",     str(batch_size),
    ]
    if large_video:
        cmd.append("--large_video")

    print("[TrackNet] Command:")
    print("  " + " ".join(cmd))
    print()

    result = subprocess.run(cmd, capture_output=False, text=True)
    # capture_output=False → TrackNet's tqdm progress bar prints live

    if result.returncode != 0:
        raise RuntimeError(
            f"TrackNetV3 predict.py exited with code {result.returncode}.\n"
            "Check the output above for the error message."
        )

    import shutil
    
    # TrackNet wrongly saves it next to the input video
    rogue_csv = Path(video_path).parent / f"{video_stem}_ball.csv"

    if rogue_csv.exists():
        # Move it from test_assets/ to results/shuttle_out/
        shutil.move(str(rogue_csv), str(expected_csv))
        print(f"[TrackNet] Intercepted CSV from video folder and moved to: {expected_csv}")
    elif not expected_csv.exists():
        # Total failure fallback
        raise FileNotFoundError(
            f"TrackNetV3 finished but no CSV found in {raw_dir} OR {rogue_csv.parent}.\n"
        )

    print(f"[TrackNet] Output CSV confirmed: {expected_csv}")
    return expected_csv


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 3 — PARSE CSV
# ─────────────────────────────────────────────────────────────────────────────
def parse_tracknet_csv(csv_path: Path, video_path: str) -> np.ndarray:
    """
    Parse TrackNetV3 CSV → (N_frames, 2) float64 array.

    TrackNetV3 CSV format (exact columns):
        Frame, Visibility, X, Y
        Frame      : 0-based frame index
        Visibility : 1 = shuttle detected, 0 = not detected
        X, Y       : pixel coordinates (0,0 when Visibility==0)

    The CSV contains exactly one row per frame where the shuttle was
    processed.  We rebuild a dense array indexed by frame number,
    filling undetected frames with NaN.

    Args
    ────
    csv_path   : path to {stem}_ball.csv
    video_path : used only to get total frame count for array sizing

    Returns
    ───────
    (N_total_frames, 2) float64  — NaN rows = undetected
    """
    # Get total frame count from video so the array covers every frame
    cap    = cv2.VideoCapture(str(video_path))
    n_total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()

    # Initialise all frames as undetected
    pts = np.full((n_total, 2), np.nan, dtype=np.float64)

    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)

        # Normalise header names to lowercase for robustness
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header row: {csv_path}")

        col = {h.strip().lower(): h.strip() for h in reader.fieldnames}
        # TrackNetV3 exact column names: Frame, Visibility, X, Y
        frame_col = col.get("frame",      col.get("frame_id", "Frame"))
        vis_col   = col.get("visibility", col.get("vis",      "Visibility"))
        x_col     = col.get("x",          col.get("ball_x",   "X"))
        y_col     = col.get("y",          col.get("ball_y",   "Y"))

        rows_read = 0
        for row in reader:
            try:
                frame_idx = int(row[frame_col])
                vis       = int(row[vis_col])
                x         = float(row[x_col])
                y         = float(row[y_col])
            except (KeyError, ValueError):
                continue

            rows_read += 1
            if frame_idx >= n_total:
                # CSV may be longer than video (edge case with padding)
                continue

            if vis == 1 and not (x == 0 and y == 0):
                pts[frame_idx] = [x, y]
            # vis == 0  →  stays NaN

    n_detected = int(np.sum(~np.any(np.isnan(pts), axis=1)))
    print(f"  CSV rows read   : {rows_read}")
    print(f"  Video frames    : {n_total}")
    print(f"  Detected frames : {n_detected}  ({100*n_detected/n_total:.1f}%)")

    return pts


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 4 — POST-PROCESSING
# ─────────────────────────────────────────────────────────────────────────────
def smooth_detections(pts: np.ndarray,
                      sigma: float = SMOOTH_SIGMA) -> np.ndarray:
    """
    Gaussian smooth detected positions only (NaN rows untouched).

    Why this is needed
    ──────────────────
    TrackNetV3 returns integer pixel coordinates (see predict.py: cx_pred,
    cy_pred are cast to int).  Consecutive detections of the same physical
    shuttle position jitter by ±1–2 px due to this rounding.  A light
    Gaussian (σ=1.2) on the detected sequence removes this jitter without
    affecting the genuine parabolic shape of the trajectory.
    """
    out  = pts.copy()
    mask = ~np.any(np.isnan(pts), axis=1)
    if mask.sum() < 4:
        return out   # too few points to smooth meaningfully
    for col in range(2):
        out[mask, col] = gaussian_filter1d(pts[mask, col], sigma=sigma)
    return out


def interpolate_gaps(pts: np.ndarray,
                     max_gap: int = GAP_FILL_FRAMES) -> np.ndarray:
    """
    Linear interpolation over NaN gaps of length ≤ max_gap frames.

    When to use / not use
    ─────────────────────
    Short gaps (1–5 frames): typically caused by TrackNet missing the shuttle
    on a single frame due to motion blur or occlusion by the player's body.
    Linear interpolation is accurate here because the shuttle moves nearly
    linearly over such short intervals at badminton speeds.

    Long gaps (> max_gap): genuine occlusion or shuttle out of frame.
    These are left as NaN — the physics optimiser in Module 4 is designed
    to handle missing observations and will skip NaN frames.
    """
    out = pts.copy()
    N   = len(pts)
    i   = 0
    while i < N:
        if np.any(np.isnan(out[i])):
            j = i
            while j < N and np.any(np.isnan(out[j])):
                j += 1
            gap = j - i
            if 0 < gap <= max_gap and i > 0 and j < N:
                for col in range(2):
                    out[i:j, col] = np.linspace(
                        out[i - 1, col], out[j, col], gap + 2)[1:-1]
            i = j
        else:
            i += 1
    return out


def detection_stats(pts: np.ndarray) -> dict:
    """Compute detection rate and quality grade."""
    N     = len(pts)
    valid = int(np.sum(~np.any(np.isnan(pts), axis=1)))
    rate  = valid / N if N else 0.0
    return {
        "total_frames":    N,
        "detected_frames": valid,
        "detection_rate":  rate,
        "missing_frames":  N - valid,
        "quality": (
            "EXCELLENT (>80%)"  if rate > 0.80 else
            "GOOD (60–80%)"     if rate > 0.60 else
            "POOR (<60%) — Z reconstruction accuracy will be limited"
        ),
    }


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 5 — DEBUG VIDEO
# ─────────────────────────────────────────────────────────────────────────────
def render_debug_video(video_path: str, shuttle_2d: np.ndarray,
                       out_path: str):
    """
    Writes a debug copy of the input video with:
      ● Green circle    = TrackNetV3 detected position (after post-processing)
      ● Amber trail     = last TRAIL_LEN projected positions
      ● White text      = (u, v) pixel coordinates
      ● Blue text       = "undetected" on frames with no detection
      ● Grey top-right  = frame counter
    """
    cap    = cv2.VideoCapture(str(video_path))
    fps    = cap.get(cv2.CAP_PROP_FPS) or 30.0
    W_vid  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H_vid  = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    writer = cv2.VideoWriter(
        str(out_path), cv2.VideoWriter_fourcc(*"mp4v"), fps, (W_vid, H_vid))

    fi = 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break

        # Amber fading trail
        start = max(0, fi - TRAIL_LEN)
        for j in range(start, fi):
            if j < len(shuttle_2d) and not np.any(np.isnan(shuttle_2d[j])):
                alpha = (j - start + 1) / (TRAIL_LEN + 1)
                c = (0, int(180 * alpha), int(255 * alpha))
                cv2.circle(frame, tuple(shuttle_2d[j].astype(int)),
                           3, c, -1, cv2.LINE_AA)

        # Current frame detection
        if fi < len(shuttle_2d) and not np.any(np.isnan(shuttle_2d[fi])):
            u, v = int(shuttle_2d[fi, 0]), int(shuttle_2d[fi, 1])
            cv2.circle(frame, (u, v), 7, (0, 255, 80), 2, cv2.LINE_AA)
            cv2.putText(frame, f"({u},{v})", (u + 10, v - 8),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255),
                        1, cv2.LINE_AA)
        else:
            cv2.putText(frame, "undetected", (10, H_vid - 14),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, (80, 80, 255),
                        1, cv2.LINE_AA)

        # Frame counter
        cv2.putText(frame, f"f{fi}", (W_vid - 80, 24),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, (200, 200, 200),
                    1, cv2.LINE_AA)

        writer.write(frame)
        fi += 1

    cap.release()
    writer.release()
    print(f"Debug video → {out_path}")


# ─────────────────────────────────────────────────────────────────────────────
#  SAVE / LOAD  (used by Module 4)
# ─────────────────────────────────────────────────────────────────────────────
def save_shuttle(shuttle_2d: np.ndarray, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    np.save(out_dir / "shuttle_2d.npy", shuttle_2d)
    print(f"shuttle_2d.npy → {out_dir}/shuttle_2d.npy")


def load_shuttle(shuttle_dir) -> np.ndarray:
    """Load shuttle_2d.npy saved by this module.  Called by Module 4."""
    return np.load(Path(shuttle_dir) / "shuttle_2d.npy")


def save_stats(stats: dict, out_dir: Path):
    path = out_dir / "detection_stats.txt"
    with open(path, "w") as f:
        f.write("Module 2 — Shuttle Detection Stats\n")
        f.write("=" * 44 + "\n")
        for k, v in stats.items():
            val = f"{v:.1%}" if "rate" in k else str(v)
            f.write(f"  {k:28s}: {val}\n")
    print(f"Stats → {path}")


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 4a — OPTIONAL VIDEO PREPROCESSING  (run before TrackNet for best results)
# ─────────────────────────────────────────────────────────────────────────────
def preprocess_video(
    input_path: str,
    output_path: str,
    n_bg_frames: int   = 30,
    boost_alpha: float = 2.5,
    boost_beta: float  = -40.0,
) -> str:
    """
    Background-subtract the video before feeding it to TrackNetV3.

    Why this helps
    ──────────────
    TrackNet internally uses consecutive frame triplets and subtracts a
    median background image to isolate moving objects. When static ad banners
    (Badminton4U, HSBC, Victor) are bright white on a dark background, they
    score identically to the shuttle in the heatmap — TrackNet cannot tell them
    apart because they look the same in the raw frame.

    Pre-subtracting the background before TrackNet sees the frames removes
    these static sources entirely. The shuttle — the only bright fast-moving
    object — becomes the dominant signal in the processed frame.

    Method
    ──────
    1. Compute the per-pixel median of the first n_bg_frames frames. This
       is the "background" — static elements like the court, net, banners.
    2. Subtract the background from every frame: pixel = frame - background.
    3. Apply contrast boost (alpha, beta) to amplify the residual moving
       objects (shuttle, players) against the now-dark background.
    4. Write to output_path as an mp4 for TrackNet to process.

    Parameters
    ──────────
    input_path    original video
    output_path   where to write the processed video (fed to TrackNet)
    n_bg_frames   number of frames to use for background estimation (default 30)
    boost_alpha   contrast multiplier after subtraction (default 2.5)
    boost_beta    brightness offset after subtraction (default -40)

    Returns output_path (for chaining into run_tracknet)
    """
    cap = cv2.VideoCapture(str(input_path))
    fps = float(cap.get(cv2.CAP_PROP_FPS) or 30.0)
    W   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # ── Step 1: collect background frames ────────────────────────────────────
    bg_frames = []
    for _ in range(n_bg_frames):
        ok, f = cap.read()
        if not ok:
            break
        bg_frames.append(f.astype(np.float32))

    if not bg_frames:
        cap.release()
        raise RuntimeError(f"Could not read any frames from {input_path}")

    # Median background — robust to players walking through early frames
    background = np.median(np.stack(bg_frames, axis=0), axis=0).astype(np.float32)
    print(f"  [preprocess] Background estimated from {len(bg_frames)} frames")

    # ── Step 2: process all frames ────────────────────────────────────────────
    cap.set(cv2.CAP_PROP_POS_FRAMES, 0)   # rewind
    writer = cv2.VideoWriter(
        str(output_path),
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps, (W, H)
    )

    fi = 0
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        # Subtract background, boost contrast, clip to valid range
        diff = frame.astype(np.float32) - background
        boosted = diff * boost_alpha + boost_beta
        out_frame = np.clip(boosted, 0, 255).astype(np.uint8)
        writer.write(out_frame)
        fi += 1

    cap.release()
    writer.release()
    print(f"  [preprocess] Wrote {fi} processed frames → {output_path}")
    return str(output_path)


# ─────────────────────────────────────────────────────────────────────────────
#  STEP 4b — ROBUST CLEANING  (replaces smooth + interpolate in main pipeline)
# ─────────────────────────────────────────────────────────────────────────────
def clean_detections(
    pts: np.ndarray,
    video_path: str,
    max_speed_ms: float = 120.0,
    max_gap_linear: int = 3,
    max_gap_physics: int = 8,
    smooth_sigma: float = 1.2,
) -> np.ndarray:
    """
    Physics-based post-processing pipeline.
    Removed the brittle 'banner_frac' and replaced it with a 'Static Lock' filter.
    """
    cap   = cv2.VideoCapture(str(video_path))
    fps   = float(cap.get(cv2.CAP_PROP_FPS) or 30.0)
    img_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    img_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    frames_gray = []
    while True:
        ok, f = cap.read()
        if not ok: break
        frames_gray.append(cv2.cvtColor(f, cv2.COLOR_BGR2GRAY))
    cap.release()

    N   = len(pts)
    out = pts.copy()

    px_per_m         = img_w * 0.55 / 6.7
    max_px_per_frame = max_speed_ms / fps * px_per_m * 1.4

    removed_static = removed_speed = removed_motion = 0
    filled_linear  = filled_physics = 0

    # ── A: Static Lock ("Hover") Filter ───────────────────────────────────────
    # A shuttle never hovers. If points stay within a 4-pixel radius 
    # for 3+ consecutive detections, it's a background logo.
    STATIC_FRAMES = 3
    STATIC_RADIUS = 4.0

    for i in range(N - STATIC_FRAMES + 1):
        window = out[i : i + STATIC_FRAMES]
        # Check if the whole window contains valid detections
        if not np.any(np.isnan(window)):
            # Calculate the max distance between any two points in this window
            max_dist = 0
            for p1 in window:
                for p2 in window:
                    dist = np.linalg.norm(p1 - p2)
                    if dist > max_dist:
                        max_dist = dist
            
            # If the points barely moved, it's a static background lock.
            if max_dist < STATIC_RADIUS:
                out[i : i + STATIC_FRAMES] = np.nan
                removed_static += STATIC_FRAMES

    # ── B: Speed Filter (Impossible jumps) ────────────────────────────────────
    prev_i = None
    for i in range(N):
        if np.any(np.isnan(out[i])):
            prev_i = None
            continue
        if prev_i is not None:
            dist  = float(np.linalg.norm(out[i] - out[prev_i]))
            limit = max_px_per_frame * (i - prev_i)
            if dist > limit:
                out[i] = np.nan
                removed_speed += 1
                continue
        prev_i = i

    # ── C: Motion Gate (Tightened) ────────────────────────────────────────────
    # Shrunk search radius from 32 to 8. This prevents players running nearby 
    # from triggering a false positive motion validation.
    SEARCH_R   = 8     
    MOT_THRESH = 12.0  
 
    for i in range(N):
        if np.any(np.isnan(out[i])):
            continue
        pf, nf = i - 1, i + 1
        if pf < 0 or nf >= len(frames_gray):
            continue 
 
        u, v = int(out[i, 0]), int(out[i, 1])
        x1 = max(0, u - SEARCH_R);  x2 = min(img_w, u + SEARCH_R)
        y1 = max(0, v - SEARCH_R);  y2 = min(img_h, v + SEARCH_R)
 
        pp = frames_gray[pf][y1:y2, x1:x2].astype(np.float32)
        pn = frames_gray[nf][y1:y2, x1:x2].astype(np.float32)
 
        if float(np.max(np.abs(pn - pp))) < MOT_THRESH:
            out[i] = np.nan
            removed_motion += 1

    # ── D: Gap Fill ───────────────────────────────────────────────────────────
    def _physics_fill(p0, p1, gap, fps_):
        t_total = (gap + 1) / fps_
        ts      = np.arange(1, gap + 1) / fps_
        vx = (p1[0] - p0[0]) / t_total
        g_px = 9.81 * px_per_m
        vy = (p1[1] - p0[1] - 0.5 * g_px * t_total**2) / t_total
        filled_x = p0[0] + vx * ts
        filled_y = p0[1] + vy * ts + 0.5 * g_px * ts**2
        return np.stack([filled_x, filled_y], axis=1)

    i = 0
    while i < N:
        if not np.any(np.isnan(out[i])):
            i += 1
            continue

        j = i
        while j < N and np.any(np.isnan(out[j])):
            j += 1
        gap = j - i

        if i > 0 and j < N:
            p0 = out[i - 1]
            p1 = out[j]

            if gap <= max_gap_linear:
                for col in range(2):
                    out[i:j, col] = np.linspace(p0[col], p1[col], gap + 2)[1:-1]
                filled_linear += gap

            elif gap <= max_gap_physics:
                try:
                    arc = _physics_fill(p0, p1, gap, fps)
                    arc[:, 0] = np.clip(arc[:, 0], 0, img_w - 1)
                    arc[:, 1] = np.clip(arc[:, 1], 0, img_h - 1)
                    out[i:j] = arc
                    filled_physics += gap
                except Exception:
                    for col in range(2):
                        out[i:j, col] = np.linspace(p0[col], p1[col], gap + 2)[1:-1]
                    filled_linear += gap
        i = j

    # ── E: Gaussian Smooth ────────────────────────────────────────────────────
    mask = ~np.any(np.isnan(out), axis=1)
    if mask.sum() >= 4:
        for col in range(2):
            out[mask, col] = gaussian_filter1d(out[mask, col], sigma=smooth_sigma)

    print(f"  clean_detections: "
          f"−{removed_static} static/hover  −{removed_speed} speed jumps  "
          f"−{removed_motion} static pixel  "
          f"+{filled_linear} linear  +{filled_physics} physics")
    return out


# ─────────────────────────────────────────────────────────────────────────────
#  ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    ap = argparse.ArgumentParser(
        description="Module 2 — Shuttle Detection via TrackNetV3",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples
────────
  # Basic run
  python module2_shuttle_detection.py --video clip.mp4 --tracknet ./tracknet_weights

  # Faster (non-overlap mode, no temporal ensemble)
  python module2_shuttle_detection.py --video clip.mp4 --tracknet ./tracknet_weights \\
      --tn_eval_mode nonoverlap

  # Large video (prevents memory errors on long matches)
  python module2_shuttle_detection.py --video match.mp4 --tracknet ./tracknet_weights \\
      --tn_large_video
        """,
    )

    # ── Our args ──────────────────────────────────────────────────────────────
    ap.add_argument("--video",    default=str(VIDEO_PATH),
                    help="Path to input video clip")
    ap.add_argument("--tracknet", default=str(TRACKNET_DIR),
                    help="Folder containing predict.py, TrackNet_best.pt, "
                         "InpaintNet_best.pt")
    ap.add_argument("--out_dir",  default=str(SHUTTLE_OUT),
                    help="Where to save shuttle_2d.npy and debug video")
    
    # ── TrackNetV3 passthrough args ───────────────────────────────────────────
    ap.add_argument("--tn_eval_mode",  default="weight",
                    choices=["nonoverlap", "average", "weight"],
                    help="TrackNetV3 --eval_mode  (default: weight)")
    ap.add_argument("--tn_batch_size", type=int, default=4,
                    help="TrackNetV3 --batch_size  (default: 16)")
    ap.add_argument("--tn_large_video", action="store_true",
                    help="Pass --large_video to TrackNetV3 for long matches")

    # ── Preprocessing ─────────────────────────────────────────────────────────
    ap.add_argument("--preprocess", action="store_true",
                    help="Background-subtract video before TrackNet. "
                         "Removes static banners/logos at the source.")

    args = ap.parse_args()

    out_dir  = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sep = "─" * 60
    print(f"\n{sep}")
    print("MODULE 2 — Shuttle Detection")
    print(sep)

    # ── Step 1: (optional) preprocess video ──────────────────────────────────
    tracknet_input = args.video
    if args.preprocess:
        print("  [preprocess] Background subtraction …")
        proc_path = str(out_dir / "preprocessed.mp4")
        tracknet_input = preprocess_video(args.video, proc_path)

    # ── Step 2: Run TrackNetV3 ────────────────────────────────────────────────
    csv_path = run_tracknet(
        video_path  = tracknet_input,
        weights_dir = args.tracknet,
        raw_out_dir = str(out_dir),
        eval_mode   = args.tn_eval_mode,
        batch_size  = args.tn_batch_size,
        large_video = args.tn_large_video,
    )

    # ── Step 3: Parse, Filter, and Output ─────────────────────────────────────
    shuttle_2d = parse_tracknet_csv(csv_path, args.video)
    
    # Render raw unfiltered detections (Matches run_pipeline.py)
    render_debug_video(args.video, shuttle_2d, str(out_dir / "shuttle_RAW_UNFILTERED.mp4"))
    
    # Clean detections
    shuttle_2d = clean_detections(shuttle_2d, args.video)
    
    # Generate stats
    stats = detection_stats(shuttle_2d)
    print(f"Detection rate: {stats['detection_rate']:.1%}  "
          f"[{stats['quality'].split('(')[0].strip()}]")

    # Save final outputs
    save_shuttle(shuttle_2d, out_dir)
    save_stats(stats, out_dir)
    render_debug_video(args.video, shuttle_2d,
                       str(out_dir / "shuttle_detection.mp4"))

    print("Module 2 done.\n")